name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      NAME: ${{ secrets.NAME }}
      ACCOUNT_NUMBER: ${{ secrets.ACCOUNT_NUMBER }}
      TRANSFER_ACCOUNT_NUMBER: ${{ secrets.TRANSFER_ACCOUNT_NUMBER }}
      TRANSFER_VALUE: ${{ secrets.TRANSFER_VALUE }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Execute the tests
      - name: Run Playwright tests
        run: npx playwright test

      # Generates the HTML Report
      - name: Generate Allure Report
        run: npx allure generate allure-results -o allure-report

      # Comment PR with the summary
      - name: Allure Report Summary
        uses: allure-framework/allure-action@v0
        with:
          report-directory: ./allure-report
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Allows to download report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      # Publish report on GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report